services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_HUB_BASE_URL: ${NEXT_PUBLIC_HUB_BASE_URL}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    image: garapro-frontend-admin:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
