name: Build Push & Trigger Coolify

on:
  push:
    branches:
      - deploy1
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env.production
        run: |
          cat > garapro-admin-frontend/.env.production <<EOF
          NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_HUB_BASE_URL=${{ secrets.NEXT_PUBLIC_HUB_BASE_URL }}
          NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
          EOF


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./garapro-admin-frontend
          file: ./garapro-admin-frontend/Dockerfile
          push: true
          tags: |
            hoangminhfcb/garapro-frontend-admin:latest
            hoangminhfcb/garapro-frontend-admin:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
            NEXT_PUBLIC_HUB_BASE_URL=${{ secrets.NEXT_PUBLIC_HUB_BASE_URL }}
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}

      - name: Trigger Coolify deploy
        run: |
          curl -sS -X POST \
            "http://103.216.119.34:8000/api/v1/deploy?uuid=v8owg0s8ckckg0go8gwww00s&force=true" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
